실습 3: 데이터 로드 및 기본 탐색
================================
CSIC 2010 HTTP 데이터셋(csic2010_requests.csv)을 로드하고
HTTP 요청의 구조와 정상/공격 분포를 파악합니다.

실행 방법: JupyterLab에서 이 노트북을 열고 셀을 위에서부터 Shift+Enter로 순차 실행
사전 준비: python download_csic2010.py 로 csic2010_requests.csv 생성

In [67]:
# %% [Setup] 패키지 import
import pandas as pd
import numpy as np
import os

In [86]:
# %% [1] 데이터 로드
# ============================================================
# 1. 데이터 로드
# ============================================================
print("=" * 65)
print("  [실습 3] CSIC 2010 HTTP 데이터 로드 및 기본 탐색")
print("=" * 65)

# Jupyter 셀 모드에서도 동작하도록 __file__ 처리
try:
    SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
except NameError:
    SCRIPT_DIR = os.getcwd()

data_path = os.path.join(SCRIPT_DIR, "csic2010_requests10000.csv")

if not os.path.exists(data_path):
    print(f"\n  !! csic2010_requests.csv 파일이 없습니다.")
    print(f"  >> 먼저 download_csic2010.py를 실행하세요.")
    exit()

df = pd.read_csv(data_path)

print(f"\n  데이터 로드 완료!")
print(f"  파일: {data_path}")
print(f"  크기: {df.shape[0]:,}행 x {df.shape[1]}열")

=================================================================
  [실습 3] CSIC 2010 HTTP 데이터 로드 및 기본 탐색
=================================================================

  데이터 로드 완료!
  파일: C:\Users\6-112\Desktop\prj\bigdata-project\10_week\csic2010_requests10000.csv
  크기: 10,000행 x 18열

### 데이터 탐색 메서드 정리

| 메서드 | 역할 | 확인 포인트 |
|--------|------|-------------|
| `df.shape` | (행 수, 열 수) 튜플 반환 | 데이터 규모 파악 |
| `df.head()` | 처음 5행 표시 | 데이터 형태 미리보기 |
| `df.tail()` | 마지막 5행 표시 | 데이터 끝부분 확인 |
| `df.head(10)` | 처음 10행 표시 | 숫자 지정 가능 |
| `df.info()` | 컬럼별 데이터 타입, Non-Null 수 | 타입 이상, Null 존재 여부 |
| `df.describe()` | 수치형 컬럼 기술통계 | 평균, 표준편차, 최솟값, 최댓값, 사분위수 |
| `df.dtypes` | 각 컬럼의 데이터 타입 | object, int64, float64 등 확인 |
| `df.columns` | 컬럼명 목록 (Index 객체) | 오타, 공백 포함 여부 확인 |
| `df.nunique()` | 컬럼별 고유값 수 | 범주형 변수 판별 기준 |
| `df["col"].value_counts()` | 값별 빈도 (내림차순) | 범주 분포 확인 |

In [87]:
df.shape

(10000, 18)

In [88]:
df.describe()

       classification
count    10000.000000
mean         0.410500
std          0.491949
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max          1.000000

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   label            10000 non-null  object
 1   method           10000 non-null  object
 2   url              9961 non-null   object
 3   http_version     10000 non-null  object
 4   host             10000 non-null  object
 5   user_agent       10000 non-null  object
 6   pragma           10000 non-null  object
 7   cache_control    10000 non-null  object
 8   accept           9929 non-null   object
 9   accept_encoding  10000 non-null  object
 10  accept_charset   10000 non-null  object
 11  language         10000 non-null  object
 12  cookie           10000 non-null  object
 13  content_type     3016 non-null   object
 14  content_length   3016 non-null   object
 15  connection       10000 non-null  object
 16  body             3016 non-null   object
 17  classification   10000 non-null  int64
dtypes: int64(1), object(17)
memory usage: 1.4+ MB

In [72]:
df.tail()

,label,method,url,http_version,host,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,cookie,content_type,content_length,connection,body,classification
61060,Anomalous,GET,/tienda1/miembros/editar.jsp?modo=registro&log...,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=62216ADBBD9B91E17CA9AFEDCCC36275,NaN,NaN,close,NaN,1
61061,Anomalous,POST,/tienda1/miembros/editar.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=2317F5C0B1B7FAD18EB425E98DB102A3,application/x-www-form-urlencoded,Content-Length: 255,Connection: close,modo=registro&login=beaumont&password=quEratIt...,1
61062,Anomalous,GET,/tienda1/miembros/editar.jsp.bak,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=7F0BA54A88B849EF752006D388E15CDD,NaN,NaN,close,NaN,1
61063,Anomalous,GET,/tienda1/imagenes/3.gif/,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=FB018FFB06011CFABD60D8E8AD58CA21,NaN,NaN,close,NaN,1
61064,Anomalous,GET,/tienda1/imagenes/nuestratierra.jpg.BAK,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=3CC12010CDA952F123240EBAD79B55CC,NaN,NaN,close,NaN,1

In [73]:
df.nunique()

label                  2
method                 3
url                13487
http_version           1
host                   2
user_agent             1
pragma                 1
cache_control          1
accept                 1
accept_encoding        1
accept_charset         1
language               1
cookie             61065
content_type           1
content_length       382
connection             2
body               12091
classification         2
dtype: int64

In [74]:
# 해당 행의 method 컬럼만 추출
df.loc[df["content_length"].isna(), "method"].value_counts()

method
GET    43088
Name: count, dtype: int64

In [76]:
# %% [2] 기본 정보 확인
# ============================================================
# 2. 기본 정보 확인
# ============================================================
print(f"\n{'─' * 65}")
print("  [2] 데이터 기본 정보")
print(f"{'─' * 65}")

print(f"\n  전체 HTTP 요청 수: {len(df):,}건")
print(f"  컬럼 수: {df.shape[1]}개")
print(f"  메모리 사용량: {df.memory_usage(deep=True).sum() / 1024 / 1024:.1f} MB")

─────────────────────────────────────────────────────────────────
  [2] 데이터 기본 정보
─────────────────────────────────────────────────────────────────

  전체 HTTP 요청 수: 61,065건
  컬럼 수: 18개
  메모리 사용량: 72.4 MB

In [77]:
# %% [4] 라벨 분포 ★★★ (Normal vs Anomalous)
# ============================================================
# 4. 라벨(Label) 분포 확인 ★★★
# ============================================================
print(f"\n{'─' * 65}")
print("  [4] 라벨 분포 (Normal vs Anomalous) ★")
print(f"{'─' * 65}")

label_counts = df["label"].value_counts()
label_ratio = df["label"].value_counts(normalize=True) * 100

print(f"\n  {'라벨':<15s} | {'건수':>8s} | {'비율':>6s} | 시각화")
print(f"  {'─' * 15}-+-{'─' * 8}-+-{'─' * 6}-+-{'─' * 30}")

for label in label_counts.index:
    count = label_counts[label]
    ratio = label_ratio[label]
    bar = "█" * int(ratio / 2)
    print(f"  {label:<15s} | {count:>8,} | {ratio:>5.1f}% | {bar}")

print(f"\n  >> 정상({label_counts.get('Normal', 0):,}건) vs "
      f"공격({label_counts.get('Anomalous', 0):,}건)")

─────────────────────────────────────────────────────────────────
  [4] 라벨 분포 (Normal vs Anomalous) ★
─────────────────────────────────────────────────────────────────

  라벨              |       건수 |     비율 | 시각화
  ───────────────-+-────────-+-──────-+-──────────────────────────────
  Normal          |   36,000 |  59.0% | █████████████████████████████
  Anomalous       |   25,065 |  41.0% | ████████████████████

  >> 정상(36,000건) vs 공격(25,065건)

In [78]:
df["label"].value_counts()

label
Normal       36000
Anomalous    25065
Name: count, dtype: int64

In [79]:
# %% [5] HTTP 메서드 분포
# ============================================================
# 5. HTTP 메서드 분포
# ============================================================
print(f"\n{'─' * 65}")
print("  [5] HTTP 메서드 분포")
print(f"{'─' * 65}")

method_counts = df["method"].value_counts()
for method, count in method_counts.items():
    pct = count / len(df) * 100
    bar = "█" * int(pct / 2)
    print(f"  {method:6s}: {count:>8,}건 ({pct:5.1f}%) {bar}")

─────────────────────────────────────────────────────────────────
  [5] HTTP 메서드 분포
─────────────────────────────────────────────────────────────────
  GET   :   43,088건 ( 70.6%) ███████████████████████████████████
  POST  :   17,580건 ( 28.8%) ██████████████
  PUT   :      397건 (  0.7%)

In [80]:
# %% [6] 메서드 × 라벨 교차 분석
# ============================================================
# 6. 메서드별 정상/공격 교차 분석
# ============================================================
print(f"\n{'─' * 65}")
print("  [6] 메서드별 정상/공격 분포")
print(f"{'─' * 65}")

cross = pd.crosstab(df["method"], df["label"])
print(f"\n{cross.to_string()}")

# 공격 비율이 높은 메서드 확인
for method in cross.index:
    total = cross.loc[method].sum()
    anomalous = cross.loc[method].get("Anomalous", 0)
    ratio = anomalous / total * 100 if total > 0 else 0
    print(f"\n  {method}: 공격 비율 {ratio:.1f}%", end="")
    if ratio > 30:
        print(" ← 공격 비율 높음!", end="")
print()

─────────────────────────────────────────────────────────────────
  [6] 메서드별 정상/공격 분포
─────────────────────────────────────────────────────────────────

label   Anomalous  Normal
method
GET         15088   28000
POST         9580    8000
PUT           397       0

  GET: 공격 비율 35.0% ← 공격 비율 높음!
  POST: 공격 비율 54.5% ← 공격 비율 높음!
  PUT: 공격 비율 100.0% ← 공격 비율 높음!

In [81]:
# %% [7] 실제 HTTP 요청 샘플 ★★★
# ============================================================
# 7. 실제 HTTP 요청 확인 ★★★
# ============================================================
print(f"\n{'─' * 65}")
print("  [7] 실제 HTTP 요청 샘플 확인 ★")
print(f"{'─' * 65}")

# 정상 요청 1건
print(f"\n  ═══ 정상 요청 (Normal) ═══")
normal = df[df["label"] == "Normal"].iloc[0]
print(f"  메서드: {normal['method']}")
print(f"  URL:    {normal['url'][:100]}{'...' if len(str(normal['url'])) > 100 else ''}")
print(f"  쿠키:   {str(normal['cookie'])[:60]}{'...' if len(str(normal['cookie'])) > 60 else ''}")
body = str(normal["body"]) if pd.notna(normal["body"]) and normal["body"] else "(없음)"
print(f"  본문:   {body[:100]}")

# 공격 요청 3건
print(f"\n  ═══ 공격 요청 (Anomalous) — 3건 ═══")
anomalous = df[df["label"] == "Anomalous"].sample(3, random_state=42)
for i, (_, row) in enumerate(anomalous.iterrows(), 1):
    print(f"\n  --- 공격 #{i} ---")
    print(f"  메서드: {row['method']}")
    url_display = str(row["url"])[:120]
    print(f"  URL:    {url_display}{'...' if len(str(row['url'])) > 120 else ''}")
    body = str(row["body"]) if pd.notna(row["body"]) and row["body"] else "(없음)"
    print(f"  본문:   {body[:120]}{'...' if len(body) > 120 else ''}")
    print(f"  → 1교시에서 배운 공격 패턴을 찾아보세요!")

─────────────────────────────────────────────────────────────────
  [7] 실제 HTTP 요청 샘플 확인 ★
─────────────────────────────────────────────────────────────────

  ═══ 정상 요청 (Normal) ═══
  메서드: GET
  URL:    /tienda1/index.jsp
  쿠키:   JSESSIONID=1F767F17239C9B670A39E9B10C3825F4
  본문:   (없음)

  ═══ 공격 요청 (Anomalous) — 3건 ═══

  --- 공격 #1 ---
  메서드: GET
  URL:    /tienda1/miembros/editar.jsp?modo=registro&login=chi-yin&password=zAfIo&nombre=Amael&apellidos=Casselle+Cullell&email=va...
  본문:   (없음)
  → 1교시에서 배운 공격 패턴을 찾아보세요!

  --- 공격 #2 ---
  메서드: GET
  URL:    /tienda1/publico/anadir.jsp?id=2%2F&nombre=Jam%F3n+Ib%E9rico&precio=39&cantidad=81&B1=A%F1adir+al+carrito
  본문:   (없음)
  → 1교시에서 배운 공격 패턴을 찾아보세요!

  --- 공격 #3 ---
  메서드: GET
  URL:    /tienda1/miembros/editar.jsp?modo=registro&login=teodoro&password=b9h%FA4a&nombre=Meliano&apellidos=Leiro+Bald%ED&email=...
  본문:   (없음)
  → 1교시에서 배운 공격 패턴을 찾아보세요!

CSIC 2010 데이터셋의 전형적인 경로 기반 정찰(Path-based Reconnaissance) 공격입니다.

각 공격 분석
공격 #1 — 기본 샘플 파일 탐색 (Default File Probing)

/WebSphereSamples/SingleSamples/Increment/increment.html
IBM WebSphere 설치 시 기본 제공되는 샘플 애플리케이션 경로
관리자가 운영 서버에서 삭제하지 않은 기본 샘플을 노려 알려진 취약점 악용
정상 사용자는 절대 접근하지 않는 경로
공격 #2 — 경로 파라미터 변조 (Path Manipulation)

/tienda1/publico/carrito.jsp/asf-logo-wide
                          ↑
                   JSP 뒤에 가짜 경로 추가
.jsp 확장자 뒤에 부가 경로(/asf-logo-wide)를 붙여 서버의 경로 파싱 로직 혼란 유도
일부 서버에서 인증/필터 우회 가능 (Path Confusion / Filter Bypass)
공격 #3 — 백업 파일 접근 시도 (Backup File Access)

/tienda1/global/estilos.css/asf-logo-wide.gif/.Old
                                              ↑
                                       백업 파일 확장자
끝의 .Old는 백업/이전 버전 파일을 노리는 전형적 패턴 (.bak, .old, .backup, ~ 등과 동일 부류)
소스 코드 노출, 구버전 취약점 악용 목적

In [82]:
# %% [8] URL 길이 기본 통계
# ============================================================
# 8. URL 길이 기본 통계
# ============================================================
print(f"\n{'─' * 65}")
print("  [8] URL 길이 기본 통계")
print(f"{'─' * 65}")

df["url_length"] = df["url"].str.len()

print(f"\n  {'구분':<12s} | {'평균':>8s} | {'중앙값':>8s} | {'최대':>8s}")
print(f"  {'─' * 12}-+-{'─' * 8}-+-{'─' * 8}-+-{'─' * 8}")

for label in ["Normal", "Anomalous"]:
    subset = df[df["label"] == label]["url_length"]
    print(f"  {label:<12s} | {subset.mean():>8.0f} | {subset.median():>8.0f} | {subset.max():>8,}")

print(f"\n  >> 공격 요청의 URL이 평균적으로 더 깁니다! (공격 코드가 삽입되므로)")

─────────────────────────────────────────────────────────────────
  [8] URL 길이 기본 통계
─────────────────────────────────────────────────────────────────

  구분           |       평균 |      중앙값 |       최대
  ────────────-+-────────-+-────────-+-────────
  Normal       |       49 |       28 |    337.0
  Anomalous    |       77 |       36 |    865.0

  >> 공격 요청의 URL이 평균적으로 더 깁니다! (공격 코드가 삽입되므로)

In [83]:
# %% [9] 데이터 품질 확인
# ============================================================
# 9. 데이터 품질 확인
# ============================================================
print(f"\n{'─' * 65}")
print("  [9] 데이터 품질 확인")
print(f"{'─' * 65}")

# 결측치 확인
missing = df.isnull().sum()
missing_cols = missing[missing > 0]
print(f"\n  결측치가 있는 컬럼:")
if len(missing_cols) > 0:
    for col, cnt in missing_cols.items():
        print(f"    - {col}: {cnt:,}건")
else:
    print("    없음 (body, cookie 등은 빈 문자열)")

# 빈 body (GET 요청)
empty_body = df["body"].fillna("").eq("").sum()
print(f"\n  본문(body)이 비어있는 요청: {empty_body:,}건 (대부분 GET 요청)")

print(f"\n{'=' * 65}")
print("  실습 3 완료! 다음: streamlit run eda_visualization.py")
print(f"{'=' * 65}")

─────────────────────────────────────────────────────────────────
  [9] 데이터 품질 확인
─────────────────────────────────────────────────────────────────

  결측치가 있는 컬럼:
    - url: 214건
    - accept: 397건
    - content_type: 43,088건
    - content_length: 43,088건
    - body: 43,088건
    - url_length: 214건

  본문(body)이 비어있는 요청: 43,088건 (대부분 GET 요청)

=================================================================
  실습 3 완료! 다음: streamlit run eda_visualization.py
=================================================================

In [84]:
df.tail()

,label,method,url,http_version,host,user_agent,pragma,cache_control,accept,accept_encoding,accept_charset,language,cookie,content_type,content_length,connection,body,classification,url_length
61060,Anomalous,GET,/tienda1/miembros/editar.jsp?modo=registro&log...,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=62216ADBBD9B91E17CA9AFEDCCC36275,NaN,NaN,close,NaN,1,284.0
61061,Anomalous,POST,/tienda1/miembros/editar.jsp,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=2317F5C0B1B7FAD18EB425E98DB102A3,application/x-www-form-urlencoded,Content-Length: 255,Connection: close,modo=registro&login=beaumont&password=quEratIt...,1,28.0
61062,Anomalous,GET,/tienda1/miembros/editar.jsp.bak,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=7F0BA54A88B849EF752006D388E15CDD,NaN,NaN,close,NaN,1,32.0
61063,Anomalous,GET,/tienda1/imagenes/3.gif/,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=FB018FFB06011CFABD60D8E8AD58CA21,NaN,NaN,close,NaN,1,24.0
61064,Anomalous,GET,/tienda1/imagenes/nuestratierra.jpg.BAK,HTTP/1.1,localhost:8080,Mozilla/5.0 (compatible; Konqueror/3.5; Linux)...,no-cache,no-cache,"text/xml,application/xml,application/xhtml+xml...","x-gzip, x-deflate, gzip, deflate","utf-8, utf-8;q=0.5, *;q=0.5",en,JSESSIONID=3CC12010CDA952F123240EBAD79B55CC,NaN,NaN,close,NaN,1,39.0

In [85]:
df.describe()

       classification    url_length
count    61065.000000  60851.000000
mean         0.410464     60.522424
std          0.491922     75.604045
min          0.000000      1.000000
25%          0.000000     27.000000
50%          0.000000     29.000000
75%          1.000000     48.000000
max          1.000000    865.000000